name: Run Cron Job

on:
  schedule:
    - cron: '30 20 * * *'  # Runs every day at 8:30 PM UTC

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you need

      - name: Install Python dependencies
        run: pip install -r ./frontend/requirements.txt

      - name: Ensure bash script has execute permission
        run: chmod +x ./frontend/runall.sh

      - name: Run the bash script
        run: ./frontend/runall.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --exit-code || git commit -m "Update data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
